name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
# allow manual trigger

jobs:
  build:
    runs-on: windows-latest
    permissions: read-all

    steps:
    - uses: actions/checkout@v4

#    - name: Setup .NET
#      uses: actions/setup-dotnet@v4
#      with:
#        dotnet-version: 9.0.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Build DLL
      run: dotnet publish cs/testexport.csproj -r win-x64 -c:Release -p:Platform=x64 -o Out/DLL

    - name: Build LIB
      run: dotnet publish cs/testexport.csproj -r win-x64 -c:Release -p:Platform=x64 -p:NativeLib=Static -o Out/LIB
      
    - name: Build CPP DLL
      run: msbuild cpp_dll/testexportdll.vcxproj -t:rebuild -p:OutDir="../Out/CPPDLL/" -p:Configuration=Release -p:Platform=x64

    - name : Upload
      uses: actions/upload-artifact@v4.3.5
      with:
        name: Exports 
        path: Out/*

    - name : Upload
      uses: actions/upload-artifact@v4.3.5
      with:
        name: ExportsCPP
        path: testexportdll/x64/*

    - name: Build EXE
      run: msbuild cpp/testexportexe.vcxproj -t:rebuild -p:OutDir="../Out/CPP/" -p:Configuration=Release -p:Platform=x64

    - name : Upload
      uses: actions/upload-artifact@v4.3.5
      with:
        name: testexport 
        path: Out/*

    - name: TEST
      run: |
        copy Out/DLL/testexport.dll Out/CPP
        Out/CPP/testexportexe.exe
